[profile.default]
src = "contracts"
out = "out"
script = "scripts"
libs = [ "dependencies" ]

solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
baseSepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

[profile.default.lint]
lint_on_build = true

[soldeer]
remappings_regenerate = false

[dependencies]
forge-std = { version = "v1.14.0", git = "https://github.com/foundry-rs/forge-std.git", tag = "v1.14.0" }
"@openzeppelin-contracts" = "5.5.0"
"@openzeppelin-contracts-upgradeable" = "5.5.0"
